### ISSUE TITLE
External specification: import fails

### ISSUE THREAD

**Issue by madig** [fonttools/fontbakery#1886]
I wrote this specification module:
```Python
from fontbakery.checkrunner import Section
from fontbakery.fonts_spec import spec_factory

spec_imports = (
    (
        "fontbakery.specifications",
        (
            "general",
            "cmap",
            "head",
            "os2",
            "post",
            "name",
            "hhea",
            "dsig",
            "hmtx",
            "gpos",
            "gdef",
            "kern",
            "glyf",
            "prep",
            "fvar",
            "shared_conditions",
        ),
    ),
)


def check_filter(checkid, font=None, **iterargs):
    if checkid in (
        "com.google.fonts/check/035",
        "com.google.fonts/check/036",
        "com.google.fonts/check/037",
        "com.google.fonts/check/038",
        "com.google.fonts/check/039",
    ):
        return False, ("Skipping external tools.")
    return True, None


specification = spec_factory(default_section=Section("Dalton Maag OpenType"))
specification.auto_register(globals(), filter_func=check_filter)
```
Running it fails with this error on Python 3.6:
```
> poetry script damacheckot -n -C ..\stroudley\build\unhinted\Stroudley_Bd.otf
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\UsersLocal\nikolaus.waxweiler\Development\damacheck\damacheck\cli.py", line 14, in check_opentype
    from .dama_ot import specification
  File "C:\UsersLocal\nikolaus.waxweiler\Development\damacheck\damacheck\dama_ot.py", line 27, in <module>
    specification.auto_register(globals(), filter_func=check_filter)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\pypoetry\Cache\virtualenvs\damacheck-py3.6\lib\site-packages\fontbakery\checkrunner.py", line 1442, in auto_register
    all_items = list(symbol_table.values()) + self._load_spec_imports(symbol_table)
  File "C:\Users\nikolaus.waxweiler\AppData\Local\pypoetry\Cache\virtualenvs\damacheck-py3.6\lib\site-packages\fontbakery\checkrunner.py", line 1410, in _load_spec_imports
    results += [getattr(module, name) for name in names]
  File "C:\Users\nikolaus.waxweiler\AppData\Local\pypoetry\Cache\virtualenvs\damacheck-py3.6\lib\site-packages\fontbakery\checkrunner.py", line 1410, in <listcomp>
    results += [getattr(module, name) for name in names]
AttributeError: module 'fontbakery.specifications' has no attribute 'general'
```
Importing it manually in a Python shell (inside the same venv) works...

**Comment by graphicore** [comment]
I think this looks good (so it's a bug). Does it work in python 2?

**Comment by madig** [comment]
Hm. Nope?
```
> python
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "C:\Users\nikolaus.waxweiler\python-repl-init.py", line 4, in <module>
    from pathlib import Path
ImportError: No module named pathlib
>>> import fontbakery.commands.check_specification
>>> import damacheck.dama_ot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "damacheck\dama_ot.py", line 42, in <module>
    specification.auto_register(globals(), filter_func=check_filter)
  File "c:\userslocal\nikolaus.waxweiler\development\fontbakery\lib\fontbakery\checkrunner.py", line 1464, in auto_register
    all_items = list(symbol_table.values()) + self._load_spec_imports(symbol_table)
  File "c:\userslocal\nikolaus.waxweiler\development\fontbakery\lib\fontbakery\checkrunner.py", line 1432, in _load_spec_imports
    results += [getattr(module, name) for name in names]
AttributeError: 'module' object has no attribute 'general'
```

**Comment by graphicore** [comment]
This should work:

```py
spec_imports = (
  "fontbakery.specifications.general",
  "fontbakery.specifications.cmap",
  "fontbakery.specifications.head",
  "fontbakery.specifications.os2",
  "fontbakery.specifications.post",
  "fontbakery.specifications.name",
  "fontbakery.specifications.hhea",
  "fontbakery.specifications.dsig",
  "fontbakery.specifications.hmtx",
  "fontbakery.specifications.gpos",
  "fontbakery.specifications.gdef",
  "fontbakery.specifications.kern",
  "fontbakery.specifications.glyf",
  "fontbakery.specifications.prep",
  "fontbakery.specifications.fvar",
  "fontbakery.specifications.shared_conditions"
)
```

`_load_spec_imports` needs tinkering to do what you want. Currently, if an item is a tuple, the first element is the `module` and the second is the `names` to import from that module.

```py
module_name, names = item
```

However, if the first element is only "dots" (`.`) a relative import style is used and the names are treated as modules as well.

```py
module_names = ['{}{}'.format(module_name, name) for name in names]
names = None
```

If we can differentate between names that are meant to be names within the module and names that are meant to be sub-modules, what you tried would work.

Maybe somehow first try importing a name as a submodule?:

```py
try:
   importlib.import_module('.'joun([module_name, name)], package=package)
…

Or so?

**Comment by madig** [comment]
Hm, well, I took inspiration from https://github.com/googlefonts/fontbakery/blob/master/docs/writing-specifications.md:
```
# spec_imports can be used to mix other specifications
# into this specification. We are only using two specifications
# for this example, containing checks for the accordingly
# named tables
spec_imports = [
    ['fontbakery.specifications', ['cmap', 'head']]
]
```
Your suggestion works. 

Not sure what would be best? We're too close to meta-magic territory, imho...

**Comment by graphicore** [comment]
> Hm, well, I took inspiration from https://github.com/googlefonts/fontbakery/blob/master/docs/writing-specifications.md.

My bad! 

> Not sure what would be best? We're too close to meta-magic territory, imho...

There's a lot of meta going on here.  This case would be nice to work I think.

**Comment by graphicore** [comment]
It's different things `filter_func` for auto register flters when registering while `check_filter` causes a `SKIP` prior execution. `check_filter` can be used, i.e. to not run a check for a black listed font name.
