### ISSUE TITLE
fontbakery_version check error

### ISSUE THREAD

**Issue by hyvyys** [fonttools/fontbakery#3111]
## Observed behaviour

I have fontbakery version 0.7.33. I get this:

```
>> Check:   com.google.fonts/check/fontbakery_version
    Desc:    Do we have the latest version of FontBakery installed?
    Files:   All fonts
    * ERROR: Failed with InvalidVersion: Invalid version: '0.18ubuntu0.18.04.1'
           File "/home/adam/.local/lib/python3.6/site-packages/fontbakery/checkrunner.py", line 366, in _exec_check
             for sub_result in result:  # Might raise.
           File "/home/adam/.local/lib/python3.6/site-packages/fontbakery/profiles/universal.py", line 349, in com_google_fonts_check_fontbakery_version
             installed = str(pip_api.installed_distributions()["fontbakery"].version)
           File "/home/adam/.local/lib/python3.6/site-packages/pip_api/_installed_distributions.py", line 85, in installed_distributions
             return _new_installed_distributions()
           File "/home/adam/.local/lib/python3.6/site-packages/pip_api/_installed_distributions.py", line 77, in _new_installed_distributions
             ret[name] = Distribution(name, version, location)
           File "/home/adam/.local/lib/python3.6/site-packages/pip_api/_installed_distributions.py", line 12, in __init__
             self.version = Version(version)
           File "/home/adam/.local/lib/python3.6/site-packages/pip_api/_vendor/packaging/version.py", line 277, in __init__
             raise InvalidVersion("Invalid version: '{0}'".format(version))
```

## Expected behaviour

Since this is the version listed as current, I'd expect no fail or error to be raised.

## Resources and exact process needed to replicate

Install fontbakery on Ubuntu 18.04.2 LTS (WSL, in case that matters):
`python3 -m pip install fontbakery`
Run fontbakery on any font.

**Comment by felipesanches** [comment]
this looks like there may be something broken in your set of locally installed python packages. This may be a problem in your system setup rather than an actual FontBakery issue. Let's try to investigate...

**Comment by felipesanches** [comment]
well... one way to show this is not fontbakery related would be by creating a new `example.py` file with these two lines:

```
import pip_api
print(pip_api.installed_distributions())
```

then run it with `python example.py` and let me know what you get as output ;-)

**Comment by felipesanches** [comment]
My guess is that you will likely get the same `InvalidVersion` exception.

**Comment by hyvyys** [comment]
You're right. This is what I got:

```
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    print(pip_api.installed_distributions())
  File "/home/adam/.local/lib/python3.6/site-packages/pip_api/_installed_distributions.py", line 85, in installed_distributions
    return _new_installed_distributions()
  File "/home/adam/.local/lib/python3.6/site-packages/pip_api/_installed_distributions.py", line 77, in _new_installed_distributions
    ret[name] = Distribution(name, version, location)
  File "/home/adam/.local/lib/python3.6/site-packages/pip_api/_installed_distributions.py", line 12, in __init__
    self.version = Version(version)
  File "/home/adam/.local/lib/python3.6/site-packages/pip_api/_vendor/packaging/version.py", line 277, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
pip_api._vendor.packaging.version.InvalidVersion: Invalid version: '0.18ubuntu0.18.04.1'
```

The same on Ubuntu 20.4:
```
 Failed with InvalidVersion: Invalid version: '0.23ubuntu1'
```

Is this related? https://github.com/pypa/pip/issues/9188

**Comment by simoncozens** [comment]
Looks like this is not a fontbakery problem but a b0rked Python installation, then.
