### ISSUE TITLE
Escape error when check-googlefonts

### ISSUE THREAD

**Issue by NightFurySL2001** [fonttools/fontbakery#3539]
When trying to run this command `fontbakery check-googlefonts .\WD-XLLubrifontSC-Regular.otf`, it gives an error after some checks:
```
Traceback (most recent call last):
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\sre_parse.py", line 1039, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\W'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\NKSL\AppData\Local\Programs\Python\Python39\Scripts\fontbakery.exe\__main__.py", line 7, in <module>
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\site-packages\fontbakery\cli.py", line 44, in main
    run_profile_check(subcommand_module[6:])
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\site-packages\fontbakery\cli.py", line 24, in run_profile_check
    sys.exit(check_profile_main(module.profile))
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\site-packages\fontbakery\commands\check_profile.py", line 342, in main
    distribute_generator(status_generator, [reporter.receive for reporter in reporters])
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\site-packages\fontbakery\checkrunner.py", line 594, in distribute_generator
    target(item)
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\site-packages\fontbakery\reporters\__init__.py", line 131, in receive
    self._output(event)
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\site-packages\fontbakery\reporters\terminal.py", line 189, in _output
    text = self._render_event(event)
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\site-packages\fontbakery\reporters\terminal.py", line 575, in _render_event
    self._render_event_async(print, event)
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\site-packages\fontbakery\reporters\terminal.py", line 564, in _render_event_async
    self._render_event_sync(print, e)
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\site-packages\fontbakery\reporters\terminal.py", line 463, in _render_event_sync
    formated_msg = parse_md(formated_msg)
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\site-packages\fontbakery\reporters\terminal.py", line 597, in parse_md
    formated_text = re.sub('<#MD-TABLE-'+str(i)+'#>', tables[i], formated_text)
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\re.py", line 327, in _subx
    template = _compile_repl(template, pattern)
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\re.py", line 318, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\users\nksl\appdata\local\programs\python\python39\lib\sre_parse.py", line 1042, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \W at position 103 (line 1, column 104)
```
Font: [WD-XLLubrifontSC-Regular.zip](https://github.com/googlefonts/fontbakery/files/7743444/WD-XLLubrifontSC-Regular.zip)

**Comment by NightFurySL2001** [comment]
It happens again with another font:
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 1041, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\L'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\Scripts\fontbakery.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\cli.py", line 45, in main
    run_profile_check(subcommand_module[6:])
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\cli.py", line 25, in run_profile_check
    sys.exit(check_profile_main(module.profile))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\commands\check_profile.py", line 347, in main
    distribute_generator(status_generator, [reporter.receive for reporter in reporters])
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\checkrunner.py", line 594, in distribute_generator
    target(item)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\__init__.py", line 131, in receive
    self._output(event)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\terminal.py", line 189, in _output
    text = self._render_event(event)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\terminal.py", line 575, in _render_event
    self._render_event_async(print, event)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\terminal.py", line 564, in _render_event_async
    self._render_event_sync(print, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\terminal.py", line 463, in _render_event_sync
    formated_msg = parse_md(formated_msg)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\terminal.py", line 597, in parse_md
    formated_text = re.sub('<#MD-TABLE-'+str(i)+'#>', tables[i], formated_text)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\sre_parse.py", line 1044, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \L at position 103 (line 1, column 104)
```
Font: [LXGWWenKai-Regular.zip](https://github.com/googlefonts/fontbakery/files/8785536/LXGWWenKai-Regular.zip)
 
Seems like this only affects Chinese font so far. Can it be related to using Chinese characters in `name` table of font? (given it stops right after entries checking related to `name`, e.g.:
```
 >> com.google.fonts/check/name/license
    Check copyright namerecords match license file.
    with .\LXGWWenKai-Regular.ttf

      Rationale:
      A known licensing description must be provided in the NameID 14 (LICENSE
      DESCRIPTION) entries of the name table.

      The source of truth for this check (to determine which license is in use)
      is a file placed side-by-side to your font project including the licensing
      terms.

      Depending on the chosen license, one of the following string snippets is
      expected to be found on the NameID 13 (LICENSE DESCRIPTION) entries of the
      name table:
      - "This Font Software is licensed under the SIL Open Font License, Version
      1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL"
      - "Licensed under the Apache License, Version 2.0"
      - "Licensed under the Ubuntu Font Licence 1.0."


      Currently accepted licenses are Apache or Open Font License.
      For a small set of legacy families the Ubuntu Font License may be
      acceptable as well.

      When in doubt, please choose OFL for new font projects.

     FAIL License file LICENSE.txt exists but NameID 13 (LICENSE
          DESCRIPTION) value on platform 1 (MACINTOSH) is not specified for
          that. Value was: "This Font Software is licensed under the SIL Open
          Font License, Version 1.1. This license is available with a FAQ at:
          https://scripts.sil.org/OFL" Must be changed to "Licensed under the
          Apache License, Version 2.0" [code: wrong]

     FAIL License file LICENSE.txt exists but NameID 13 (LICENSE
          DESCRIPTION) value on platform 3 (WINDOWS) is not specified for that.
          Value was: "This Font Software is licensed under the SIL Open Font
          License, Version 1.1. This license is available with a FAQ at:
          https://scripts.sil.org/OFL" Must be changed to "Licensed under the
          Apache License, Version 2.0" [code: wrong]


    Result: FAIL
```
)

**Comment by NightFurySL2001** [comment]
Related to #3750.

**Comment by simoncozens** [comment]
We now render Markdown tables directly, so this regular expression is no more.
