### ISSUE TITLE
Ensure Progress bar works on Windows

### ISSUE THREAD

**Issue by davelab6** [fonttools/fontbakery#4182]
In https://typedrawers.com/discussion/comment/62849/#Comment_62849 a user writes,

>  there’s no way to make the progress bar work [on windows]. So I always have to use -s to deactivate it.

I'm sure that is annoying :)

**Comment by ftCLI** [comment]
I wrote the comment on typedrawers. Sorry, I misspelled: I have to use -n and not -s.

Here's the full error:

```
Traceback (most recent call last):
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\Scripts\fontbakery.exe\__main__.py", line 7, in <module>
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\cli.py", line 55, in main
    run_profile_check(subcommand_module[6:])
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\cli.py", line 28, in run_profile_check
    sys.exit(check_profile_main(module.profile))
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\commands\check_profile.py", line 355, in main
    distribute_generator(status_generator, [reporter.receive for reporter in reporters])
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\checkrunner.py", line 595, in distribute_generator
    target(item)
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\__init__.py", line 132, in receive
    self._output(event)
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\terminal.py", line 189, in _output
    text = self._render_event(event)
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\terminal.py", line 601, in _render_event
    self._render_event_async(print, event)
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\terminal.py", line 593, in _render_event_async
    self._render_event_sync(print, event)
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\terminal.py", line 400, in _render_event_sync
    self.stdout.write(text)
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\terminal.py", line 125, in write
    self.flush()
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\terminal.py", line 131, in flush
    progressbar, reset_progressbar = self._draw_progressbar()
  File "C:\Users\Cesare\AppData\Local\Programs\Python\Python310\lib\site-packages\fontbakery\reporters\terminal.py", line 305, in draw_progressbar
    columns = int(columns_entry[0].split()[1])
IndexError: list index out of range
```

**Comment by davelab6** [comment]
@ftCLI thanks for the traceback!! That's very helpful

**Comment by graphicore** [comment]
Hi @ftCLI I just answered in https://github.com/googlefonts/fontbakery/issues/4189#issuecomment-1594355499 and it seems like your latest screenshot is related.

Could you try to turn off colors with `-C`? And if you are brave, try to get ANSI escape codes working in PowerShell using this documentation: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.3

**Comment by graphicore** [comment]
Yeah, the progressbar also uses ANSI escape codes, thus, so far `-n` is also required if these are not working.

**Comment by domija** [comment]
I was actually able to get it work by using the new windwos terminal app. 
![obrazek](https://github.com/googlefonts/fontbakery/assets/36168990/5034180f-ab90-41b2-aace-949e8a965e40)

**Comment by simoncozens** [comment]
I reckon #4447 will fix this, but I can't test on windows.

**Comment by ftCLI** [comment]
> I reckon #4447 will fix this, but I can't test on windows.

Works on Windows 10 21H2

![image](https://github.com/fonttools/fontbakery/assets/83063506/1cbd996f-97b1-4c8d-bf95-bb64703d1272)

![image](https://github.com/fonttools/fontbakery/assets/83063506/3176fd63-14ca-41bd-a982-69878173fd44)
