### ISSUE TITLE
`--auto-jobs` crashes in version 0.11.0

### ISSUE THREAD

**Issue by dscorbett** [fonttools/fontbakery#4481]
## Observed behavior

Running Font Bakery 0.11.0 with `--auto-jobs` crashes if many checks are active, e.g. all of `check-googlefonts`.

```
Traceback (most recent call last):
  File "/Users/dcorbett/venv-fb-crash/bin/fontbakery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/dcorbett/venv-fb-crash/lib/python3.11/site-packages/fontbakery/cli.py", line 61, in main
    run_profile_check(subcommand_module[6:])
  File "/Users/dcorbett/venv-fb-crash/lib/python3.11/site-packages/fontbakery/cli.py", line 34, in run_profile_check
    sys.exit(check_profile_main(module.profile))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dcorbett/venv-fb-crash/lib/python3.11/site-packages/fontbakery/commands/check_profile.py", line 471, in main
    runner.run(reporters)
  File "/Users/dcorbett/venv-fb-crash/lib/python3.11/site-packages/fontbakery/checkrunner.py", line 486, in run
    list(executor.map(run_a_check, self.order))
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dcorbett/venv-fb-crash/lib/python3.11/site-packages/fontbakery/checkrunner.py", line 478, in run_a_check
    reporter.receive_result(result)
  File "/Users/dcorbett/venv-fb-crash/lib/python3.11/site-packages/fontbakery/reporters/terminal.py", line 235, in receive_result
    self._console.print(
  File "/Users/dcorbett/venv-fb-crash/lib/python3.11/site-packages/rich/console.py", line 1673, in print
    with self:
  File "/Users/dcorbett/venv-fb-crash/lib/python3.11/site-packages/rich/console.py", line 865, in __exit__
    self._exit_buffer()
  File "/Users/dcorbett/venv-fb-crash/lib/python3.11/site-packages/rich/console.py", line 823, in _exit_buffer
    self._check_buffer()
  File "/Users/dcorbett/venv-fb-crash/lib/python3.11/site-packages/rich/console.py", line 2065, in _check_buffer
    self.file.flush()
    ^^^^^^^^^^^^^^^
AttributeError: 'TTXLogger' object has no attribute 'flush'
```

## Expected behavior

`--auto-jobs` should work like it did in previous versions.

**Comment by simoncozens** [comment]
We switched from multiprocessing to multithreading, and for some reason things become weirdly unstable (particularly with that TTX check) when there are too many threads going on. I don't know if it's an issue with Python's threading implementation, or just that we're not supposed to do that (some data races/etc. we didn't check for), but I'm afraid I don't know how to fix it. Multiprocessing was stable and worked reasonably well, but it was *exceptionally* complicated and made the core codebase very hard to understand.

**Comment by mrecord** [comment]
I'm also running Font Bakery 0.11.0 and getting a similar crash when exporting a html report.
(Sorry, don't mean to pile-on. I'm posting this with the hope that a similar traceback can help find a solution.)

This works without any problems: `fontbakery check-universal *.otf`
This causes a crash: `fontbakery check-universal *.otf --html fontbakery_report.html`

```
Traceback (most recent call last):
  File "/Users/mark/.pyenv/versions/3.12.0/bin/fontbakery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mark/.pyenv/versions/3.12.0/lib/python3.12/site-packages/fontbakery/cli.py", line 61, in main
    run_profile_check(subcommand_module[6:])
  File "/Users/mark/.pyenv/versions/3.12.0/lib/python3.12/site-packages/fontbakery/cli.py", line 34, in run_profile_check
    sys.exit(check_profile_main(module.profile))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mark/.pyenv/versions/3.12.0/lib/python3.12/site-packages/fontbakery/commands/check_profile.py", line 474, in main
    reporter.write()
  File "/Users/mark/.pyenv/versions/3.12.0/lib/python3.12/site-packages/fontbakery/reporters/html.py", line 50, in write
    fh.write(self.get_html())
             ^^^^^^^^^^^^^^^
  File "/Users/mark/.pyenv/versions/3.12.0/lib/python3.12/site-packages/fontbakery/reporters/html.py", line 57, in get_html
    loaders = [PackageLoader("fontbakery.reporters", "templates/html")]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mark/.pyenv/versions/3.12.0/lib/python3.12/site-packages/jinja2/loaders.py", line 323, in __init__
    raise ValueError(
ValueError: The 'fontbakery.reporters' package was not installed in a way that PackageLoader understands.
```

**Comment by felipesanches** [comment]
>   File "/Users/mark/.pyenv/versions/3.12.0/lib/python3.12/site-packages/jinja2/loaders.py", line 323, in __init__
>     raise ValueError(
> ValueError: The 'fontbakery.reporters' package was not installed in a way that PackageLoader understands.
> ```

This was fixed already and will be included in v0.11.1 (see #4479)

**Comment by felipesanches** [comment]
To be more precise, this problem is not specific to `--auto-jobs`. Naturally, the bug also happens when one specifies more than a single process with `-J <n>`. For instance, I was able to replicate it with `-J 4`.

I've also seen some corruptioni of the terminal output, but I will report it in a separate issue.

**Comment by felipesanches** [comment]
I tried now using `--quiet` alongside `--auto-jobs` in the hope of isolating the problem, but still stumbled on problems. Maybe this can provide further insight:

![Screenshot from 2024-02-05 17-41-27](https://github.com/fonttools/fontbakery/assets/213676/30d3ab65-f101-4d80-b66c-42cb5e3c1486)

**Comment by simoncozens** [comment]
Threading bugs aren't always logical, since they can involve data races and memory corruption, and we're not being careful to avoid multiple accesses to shared objects - we have no locking, atomics, or anything else. I'm hoping that as we refactor the check implementations, particularly around the use of "conditions", individual check functions will have less shared state, and so won't be able to corrupt each other.

**Comment by felipesanches** [comment]
For **com.google.fonts/check/ttx_roundtrip** we clearly need semaphores for usage of stdout & stderr: 
![image](https://github.com/fonttools/fontbakery/assets/213676/cdbd5883-f265-4417-b993-1849f7817216)

And we also need to coordinate access to stdout to ensure only one process is printing a check body (title, rationale, log messages) at any time.

**Comment by graphicore** [comment]
I'd be interested in a benchmark between multiprocessing and multithreading. As far as I understand it, the GIL of Python makes it less than ideal to run computational heavy code in multithreading. Multiprocessing has its costs as well, but the mixture of checks should make it an interesting comparison and it's the real case. I chose multithreading because I expected the checks to be more computational and less I/O heavy.
