### ISSUE TITLE
HTML reporter seems to be broken

### ISSUE THREAD

**Issue by khaledhosny** [fonttools/fontbakery#4482]
HTML reporter seems to be broken in latest version:
```
$ fontbakery check-shaping --config=fontbakery.yml Raqq.ttf --html=Raqq-shaping.html
Start ... running 5 individual check executions.

▓ [PPSPS] 100%
Total:
    ERROR: 0
    FATAL: 0
    FAIL: 0
    WARN: 0
    INFO: 0
    SKIP: 2
    PASS: 3



    Meaning of check results:

    An ERROR is something wrong with FontBakery itself, possibly a bug.
    A  FATAL is an extremely severe issue that must be addressed immediately.
    A  FAIL is a problem with the font that must be fixed.
    A  WARN is something that you should consider addressing.
    An INFO result simply prints something useful. Typically stats.
    A  PASS means the font looks good for the given checking routine.
And a  SKIP happens when the check does not apply to the given font.

    If you get ERRORs, please help us improve the tool by reporting them at
    https://github.com/fonttools/fontbakery/issues (but other kinds of bug
    reports and/or feature requests are also always welcome, of course!)



DONE!
Traceback (most recent call last):
  File "/venv2/bin/fontbakery", line 8, in <module>
    sys.exit(main())
  File "/venv2/lib/python3.10/site-packages/fontbakery/cli.py", line 61, in main
    run_profile_check(subcommand_module[6:])
  File "/venv2/lib/python3.10/site-packages/fontbakery/cli.py", line 34, in run_profile_check
    sys.exit(check_profile_main(module.profile))
  File "/venv2/lib/python3.10/site-packages/fontbakery/commands/check_profile.py", line 474, in main
    reporter.write()
  File "/venv2/lib/python3.10/site-packages/fontbakery/reporters/html.py", line 50, in write
    fh.write(self.get_html())
  File "/venv2/lib/python3.10/site-packages/fontbakery/reporters/html.py", line 57, in get_html
    loaders = [PackageLoader("fontbakery.reporters", "templates/html")]
  File "/venv2/lib/python3.10/site-packages/jinja2/loaders.py", line 323, in __init__
    raise ValueError(
ValueError: The 'fontbakery.reporters' package was not installed in a way that PackageLoader understands.
```

**Comment by khaledhosny** [comment]
(PS. why there is no issue template for general bug reports?)

**Comment by khaledhosny** [comment]
Duplicate of #4479
