### ISSUE TITLE
fontbakery.com error: freetype_rasterizer not found

### ISSUE THREAD

**Issue by eweracs** [fonttools/fontbakery#4893]
## Observed behaviour

When dropping a font file onto the fontbakery.com site and running FB, the following error is immediately reported:
```
Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 363, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 5, in 
  File "/home/pyodide/fbwebapi.py", line 79, in run_fontbakery
    profile = profile_factory(import_module("fontbakery.profiles." + profilename))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/fontbakery/fonts_profile.py", line 151, in profile_factory
    add_checks_to_nascent_profile(
  File "/lib/python3.11/site-packages/fontbakery/fonts_profile.py", line 116, in add_checks_to_nascent_profile
    raise ValueError(f"Check '{check}' not found")
ValueError: Check 'freetype_rasterizer' not found
```

## Expected behaviour

This shouldn't happen.

## Resources and steps needed to reproduce
Drop any font file onto the fontbakery.com site and run any profile.

**Comment by andreubalius** [comment]
Also the same problem with Type Network:

**Comment by eweracs** [comment]
Yes, as I pointed out, this occurs with any profile.

**Comment by simoncozens** [comment]
I think I've fixed this now.
