### ISSUE TITLE
Public instance http://fontbakery.com/ does not work

### ISSUE THREAD

**Issue by mlpo** [fonttools/fontbakery#4952]
## Observed behaviour

[Public instance of fontbakery](http://fontbakery.com/) crashes with the following error:
```
Traceback (most recent call last):
  File "/lib/python311.zip/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 1209, in _gcd_import
  File "", line 1181, in _find_and_load
  File "", line 1152, in _find_and_load_unlocked
  File "", line 690, in _load_unlocked
  File "", line 940, in exec_module
  File "", line 241, in _call_with_frames_removed
  File "/home/pyodide/fbwebapi.py", line 35, in 
    import glyphsets
  File "/lib/python3.11/site-packages/glyphsets/__init__.py", line 10, in 
    import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

## Expected behaviour

Public instance should work.

## Resources and steps needed to reproduce

Access the public instance: http://fontbakery.com/.

**Comment by guidoferreyra** [comment]
Having the same problem here.

**Comment by simoncozens** [comment]
I'm working on this, but it's complicated; recently changes to glyphsets have added a few imports and also some asserts that we can't fulfil on WASM.
